# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://beinformed.life/"
DefaultContentLanguage  = "en"
title                   = "Be Informed"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
pluralizeListTitles     = false
disableLanguages        = [""]

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "reddit", "pinterest", "email"]

  [params.meta]
    description         = "Be Informed : News and resources related to COVID - ID - 2020 - 5G - AI."
    author              = "Be Informed"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Be Informed"
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Be Informed"
    paragraph             = "News and resources related to COVID - ID - 2020 - 5G - AI."
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/Logo-150w.png"
      shape               = "rectangle"
      width               = ""
      alt                 = "Be Informed Pheonix Logo"

  [params.sidebar]
    about               = "Avalon Awake / Be Informed is a pan global information matrix of humanitarians focused on being a positive force for good in the world, helping to support, awaken and empower our global family with resources to become pro-active in creating positive change in the world.  "
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Latest News"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Rabbit Warren"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  
  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Española"
    weight              = 2

 

[social]
 
  # Social Networks
  # facebook              = "example"
  # googleplus            = ""
  # reddit                = "example"
  # quora                 = ""
  youtube               = ""
  # vimeo                 = ""
    # WeChat and QQ need testing.
  # instagram             = "example"
  twitter               = "example"
  pinterest             = "example"
  telegram              = "example"
  # Email
  email                 = "example"
