theme = "hugo-sugoi"
baseURL = "https://beinformed2020.netlify.app/"
languageCode = "en-us"
title = "Be Informed 2020"
summaryLength = 20
paginate = 5


[params]
favicon = "images/favicon.png"
herotitle = "Whatever intro/homepage-header text you want can go here ..."

[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-home'></i>"
        url     = "about"
        weight  = -1
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -2
